services:
    app:
        build:
            context: . # Dockerfileの場所
            dockerfile: ./infra/php/Dockerfile # Dockerfileの名前（デフォルトで "Dockerfile"）
        container_name: laravel_app
        volumes:
            - .:/var/www/html # Laravelのソースコードをマウント
        env_file:
            - ./infra/.env # Docker用の環境変数ファイル
        depends_on:
            - db # データベースへの依存関係

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        volumes:
            - .:/var/www/html # 同様にソースコードをマウント
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf # Nginxの設定
        ports:
            - "8000:80" # ホストのポート8000をNginxの80ポートにマッピング
        depends_on:
            - app # Laravelコンテナへの依存関係

    db:
        image: postgres:latest
        container_name: postgres_db
        env_file:
            - ./infra/.env # Docker用の環境変数ファイル
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        env_file:
            - ./infra/.env # Docker用の環境変数ファイル
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        ports:
            - "5050:80"
        depends_on:
            - db

volumes:
    db_data:
    pgadmin_data:
