services:
    php:
        build:
            context: ../
            dockerfile: ./docker/php/Dockerfile
        container_name: health-management-php
        volumes:
            - ../:/var/www/html
            - ../docker/php/php.ini:/usr/local/etc/php/php.ini
            - ../docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ../docker/php/cron_jobs:/etc/cron.d/laravel_cron
        environment:
            PHP_IDE_CONFIG: "serverName=docker"
            DOCKER_PHP_MEMORY_LIMIT: ${DOCKER_PHP_MEMORY_LIMIT}
            DOCKER_PHP_UPLOAD_MAX_FILESIZE: ${DOCKER_PHP_UPLOAD_MAX_FILESIZE}
            DOCKER_PHP_POST_MAX_SIZE: ${DOCKER_PHP_POST_MAX_SIZE}
            DOCKER_PHP_MAX_EXECUTION_TIME: ${DOCKER_PHP_MAX_EXECUTION_TIME}
            DOCKER_PHP_DISPLAY_ERRORS: ${DOCKER_PHP_DISPLAY_ERRORS}
            DOCKER_PHP_XDEBUG_ENABLED: ${DOCKER_PHP_XDEBUG_ENABLED:-0}
            DOCKER_PHP_XDEBUG_MODE: ${DOCKER_PHP_XDEBUG_MODE:-off}
            DOCKER_PHP_XDEBUG_START_WITH_REQUEST: ${DOCKER_PHP_XDEBUG_START_WITH_REQUEST:-no}
            DOCKER_PHP_CLIENT_HOST: ${DOCKER_PHP_CLIENT_HOST}
            DOCKER_PHP_CLIENT_PORT: ${DOCKER_PHP_CLIENT_PORT:-9003}
            DB_HOST: ${DOCKER_DB_HOST}
            DB_PORT: ${DOCKER_DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_SCHEMA: ${DB_SCHEMA}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - postgres
    nginx:
        image: nginx:alpine
        container_name: health-management-nginx
        volumes:
            - ../:/var/www/html
            - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - php

    postgres:
        image: postgres:16-alpine
        container_name: health-management-postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-laravel}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${DB_USERNAME:-laravel} -d ${DB_DATABASE:-laravel}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4:7.8
        container_name: health-management-pgadmin
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${DOCKER_PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${DOCKER_PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres
        restart: unless-stopped

volumes:
    postgres_data:
    pgadmin_data:
